### ISSUE TITLE
Negative HPs are sometimes incorrectly calculated

### ISSUE THREAD

**Issue by caioalonso** [telemmo/telemmo#100] opened 2017-02-22 11:36 UTC
When a battle is finished, it seems that the negative HP of the defeated party is sometimes one point less than the correct value.

For example:
```
🔸🎯 4 💢 17 ✨ 16
Troll dealt 14 damage
ee's hp: 1 / 67

🔹🎯 4 💢 7 ✨ 13
ee dealt 6 damage
Troll's hp: 30 / 81

🔸🎯 7 💢 6 ✨ 16
Troll dealt 3 damage
ee's hp: -3 / 67
```

Shouldn't it be `-2 / 67`?

I haven't been able to reproduce this 100% of the time. It only happens in some battles.

**Comment by MarcoWorms** [comment] 2017-02-24 14:07
Well, it's not a bug because the numbers are decimals and i just hid them. It can definetively be improve though, showing the decimals or rounding the values to ingeres for instance.

**Comment by MarcoWorms** [comment] 2017-03-21 04:19
Closing this since it's not a bug (lol) but I'll try to make the visualization more precise.

**Closed by MarcoWorms** 2017-03-21 04:19 UTC
